spring.config.import=optional:file:.env[.properties]

spring.application.name=LandblumeWebsite
server.servlet.context-path=/landblume
server.port=${SERVER_PORT}
server.encoding.charset=UTF-8
server.encoding.force=true
server.encoding.error.whitelabel.enabled=false

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?currentSchema=${DB_SCHEMA}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

spring.liquibase.enable=true
spring.liquibase.default-schema=${DB_SCHEMA}
spring.liquibase.user=${LIQUIBASE_USER}
spring.liquibase.password=${LIQUIBASE_PASSWORD}
spring.liquibase.change-log=classpath:liquibase/changelog/db.changelog-main.yaml
spring.liquibase.parameters.schema=${DB_SCHEMA}
spring.liquibase.parameters.user.app=${DB_USER}
spring.liquibase.parameters.user.liquibase=${LIQUIBASE_USER}